spring:
  data:
    solr:
      zk-host: 192.168.1.3:2181,192.168.1.3:2182,192.168.1.3:2183
      default-collection: myCloud
      repositories:
        enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
#dubbo????
  application:
    name: searchService-consumer
server:
  port: 80
dubbo:
  registry:
    address: zookeeper://192.168.1.11:2181