server:
  port: 80
spring:
  application:
    name: consumer-cart
#???????
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
cart:
  key: cartKey


#?????
http:
  maxTotal: 100
  #???
  defaultMaxPerRoute: 20
  # ?????????
  connectTimeout: 1000
  # ?????????????
  connectRequestTimeout: 1000
  # ?????????
  socketTimeout: 10000
  # ?????????????
  staleConnectionCheckEnabled: true
dubbo:
  registry:
    address: zookeeper://192.168.1.11:2181
