#最大连接数
http:
  maxTotal: 100
#并发数
  defaultMaxPerRoute: 20
# 创建连接的最长时间
  connectTimeout: 1000
# 从链接池获取连接的最长时间
  connectRequestTimeout: 1000
# 数据传输的最长时间
  socketTimeout: 10000
# 提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
