# ?????
spring:
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
#???????
  application:
    name: listService-passport

#??????
dubbo:
  registry:
    address: zookeeper://192.168.1.11:2181

#?????
server:
  port: 80
#??????key
user:
  key: userKey

